### ISSUE TITLE
it double loads the script and it glitches

### ISSUE THREAD

**Issue by themusicglitch** [wernser412/Hack-Cursors.io#1]

**Comment by themusicglitch** [comment]
and it gets stuck like that forever

**Comment by wernser412** [comment]
Important:

1.- Use the adguard extension --- https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=es

 2.-In configuration -> user rules to type "http://cursors.io/client_out.js"
